Text_intro = ('<?xml version="1.0"?>\n'
              '<configuration template="%APPPATH%\\templates\SoftScope.pct" version="3"><data><softScopeSession>\n'
              '			<commSettings>Modbus:1,1000,J#COM:4,38400,N,8,1,H</commSettings>\n'
              '			<target>\n'
              '				<maxTracks>20</maxTracks>\n'
              '				<maxSamples>1</maxSamples>\n'
              '				<sampleTimeBase>125000</sampleTimeBase>\n'
              '				<targetConfig><AxX_402p1 template="" version="1"/>\n'
              '				</targetConfig>\n'
              '			</target>\n'
              '			<session>\n'
              '				<acquisitionId>405</acquisitionId>\n'
              '				<numSamples>585</numSamples>\n'
              '				<triggerSource>varILoopIdRef</triggerSource>\n'
              '				<triggerSlope>1</triggerSlope>\n'
              '				<triggerValue>99</triggerValue>\n'
              '				<preTriggerTime>320</preTriggerTime>\n'
              '				<tracks>\n')
TextCentral = ('            </tracks>\n'
               '				<timePrescaler>1</timePrescaler>\n'
               '				<PLCSymTab/>\n'
               '			</session>\n'
               '			<data>\n'
               '				<graph hscale="2" triggerpos="40"><tracks>\n')
TextEnd = ('</tracks></graph>\n'
           '			</data>\n'
           '		</softScopeSession>\n'
           '	</data></configuration>\n')
Text00 = '<track><DictObject name="'
Text01 = '" index="0" subindex="0" type="5" um="V" scale="10" offs="0" shortdescr="" descr="" bitNumber=""><origin deviceid="AxX_402p1"/></DictObject></track>\n'

Text10 = '<track name="'
Text11 = '" um="" vscale="1" offset="0" color="'
Text12 = '" note="" timeshift="0">\n<samples>\n'
Text13 = '<sample time="'
Text14 = '">'
Text15 = '</sample>\n'
Text16 = '</samples></track>>\n'

ColorString = ['65535', '16776960', '16711935', '65280', '255', '16711680', '16744576', '33023']
